import "~/styles/globals.css"

import { ClerkProvider } from "@clerk/nextjs"
import { Mochiy_Pop_P_One } from "next/font/google"
import { Poppins } from "next/font/google"

import { plPL } from "@clerk/localizations"
import { ReactQueryProvider } from "~/providers/reactquery-provider"

const inter = Poppins({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400"],
})

const mochiy = Mochiy_Pop_P_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mochiy",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <ClerkProvider localization={plPL}>
        <html lang="en">
          <body
            className={`font-sans ${inter.variable} dark ${mochiy.variable}`}
          >
            {children}
          </body>
        </html>
      </ClerkProvider>
    </ReactQueryProvider>
  )
}
