import "~/styles/globals.css"

import { Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { TopNav } from "./_components/topnav"
import { Mochiy_Pop_P_One } from "next/font/google"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

const mochiy = Mochiy_Pop_P_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mochiy",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable} dark ${mochiy.variable}`}>
          <div className="grid h-screen grid-rows-[auto,1fr]">
            <TopNav />
            <main className="overflow-y-scroll ">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
